name: Z1N CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    environment: Z1N
    runs-on: ubuntu-latest
    steps:
      -
        id: get_version
        uses: battila7/get-version-action@v2
      -
        run: echo ${{ steps.get_version.outputs.version }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push z1n-erpnext-nginx
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: nginx/Dockerfile
          push: true
          tags: zirrusone:v1.0.5
      -
        name: Build and push z1n-erpnext-worker
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: worker/Dockerfile
          push: true
          tags: zirrusone:v1.0.5
